# Generated by Django 3.0.8 on 2020-07-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Питомцы')),
                ('url', models.SlugField(max_length=30, unique=True)),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
            ],
            options={
                'verbose_name': 'Питомцы',
                'verbose_name_plural': 'Питомец',
                'ordering': ['name'],
            },
        ),
    ]
